### PR TITLE
Add PKGBUILD to build on arch

### PR DESCRIPTION
**Pull request by maxfenv**
To build and package kealib on arch linux.

Ideally this would be in the [Arch User Repository](https://aur.archlinux.org/) instead of or in addition to this repo.  Just as soon as I've figured out how to do that, I'll do that!

### CODE REVIEW

**Comment by maxfenv** [comment]
I've submitted this PKGBUILD to the AUR: [](https://aur.archlinux.org/packages/libkea).  I think that rather invalidates this PR as I'd rather not maintain it in two places.

Sorry for the noise.

**Comment by maxfenv** [comment]
I should have of course searched the AUR before attempting this.  This work had already been done: https://aur.archlinux.org/packages/kealib

**Comment by gillins** [comment]
> This work had already been done:

Good to know @maxfenv. BTW any reason AUR builds the gdal plugin rather than enable KEA during the `libgdal` build? The plugin is a bit behind  upstream (eg. /vsi filesystems aren't available) for a variety of reasons. Some technical (ie plugins can't access some of the features the `hdf5` driver supplies), some because I support very old GDAL versions (especially for Arc) and some because I don't often get around to syncing with upstream...

**Comment by maxfenv** [comment]
Sorry @gillins I'm not sure what you mean.

The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kealib) in the AUR follows the instructions on the [wiki](https://github.com/ubarsc/kealib/wiki/Building-KEA-on-Ubuntu) very closely.

**Comment by gillins** [comment]
> The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kealib) in the AUR follows the instructions on the [wiki](https://github.com/ubarsc/kealib/wiki/Building-KEA-on-Ubuntu) very closely.

OK so turned out the wiki hadn't been updated to show that the KEA driver is now part of GDAL (https://gdal.org/drivers/raster/kea.html). Just updated it now, let me know if anything is unclear.

**Comment by maxfenv** [comment]
I see what you mean.  The reason is probably as follows:

`gdal` is an officially built package provided by the distribution, analogous to how `libgdal` is an official package that is provided by ubuntu.  `kealib` is a package that only exists as a build script (the PKGBUILD) in the Arch User Repository, which is a collection of user contributed and entirely unsupported packages.  This is perhaps somewhat analogous to PPAs in ubuntu.

It is not possible/sensible for a package in the official repositories to depend on a package in the Arch User Repository.  `kealib` would either have to be included in the official set of packages (unlikely, but not impossible assuming there is interest by the current maintainer of the `gdal` package) or a `gdal-kea` package could be created in the AUR that builds gdal with libkea not as a plugin.

Other than being conceptually nicer, are there any differences notable to the end user one way or the other?

**Comment by maxfenv** [comment]
I should say: I am a user of Arch Linux, I'm not a packager or one of its developers.  The above is true as far as I know, but don't take it as gospel.

**Comment by gillins** [comment]
Ah I see. Thanks for the background. I'll keep the plugin around for situations like this I guess.

> Other than being conceptually nicer, are there any differences notable to the end user one way or the other?

The main one is that the `/vsi` filesystems aren't available when KEA is built as a plugin (I need access to some of the stuff in the `hdf5` driver and this isn't available outside of the GDAL build). Other downside is that changes within GDAL break the plugin every once in a while and sometimes I don't notice until someone tells me. The internal copy is always updated. 

I was asking because conda-forge builds use the internal KEA support and that seems to work quite well.

**Pull request closed without merging**
