### PR TITLE
WIP: New implementation of kealib python bindings using libawkward

### PR DESCRIPTION
**Pull request by gillins**
### Overview

The old Python bindings gave access to the neighbours functionality in the RAT. as this isn't supported by GDAL. The implementation was a bit messy as ragged arrays don't map well into Python. They supported lists of lists (slow) or masked arrays (complex and not memory efficient). 

This PR contains a new implementation using [awkward arrays](https://awkward-array.readthedocs.io/en/latest/index.html). This seems a more "standard" way of dealing with this situation and has the advantage of working well with Numba. This is a bit of an experiment in using libawkward and also pybind11 for building Python bindings (which is required for anything using libawkward and Python).

It has ended up being a bit more messy that I would have liked but I'm keen to push through unless anyone thinks overwise (?).

### Notes

- I'm still using the old approach of taking a GDAL dataset and extracting the kea Image C++ via GetInternalHandle(). This is messy but means that you can read the data via GDAL and update/access the neighbours at the same time.
- pybind11 is contained as a git submodule pinned to the same version used by libawkward (this appears to be the standard way of including pybind11) so pass `--recurse-submodules` to `git clone`. 
- Building is now done via cmake.
- pybind11 is incredibly fussy about compiler versions. You need to be using **exactly the same compiler** that libawkward was built with. Not a slightly different minor version. Not the same version but with slightly different patches applied by your distro. The same actual binary. This a note mainly for conda users who won't usually have the conda compiler installed (although this can be overcome on Linux at least). I can work up to providing conda packages if people would like.

### Still left to do

- Installation
- A "main" script that builds neighbours of a given image using RIOS.
- Have a way of merging neighbours so that when processing an image tile by tile we can merge in new neighbours for segments that straddle a tile.
- Add a C++ implementation that given a numpy array from RIOS (with appropriate overlap) can build up neighbours for that tile. These neighbours can then be merged (using above) and this can all be called from the main script.

### CODE REVIEW

**Comment by gillins** [comment]
ping @petescarth

**Comment by gillins** [comment]
I've added a build to the `rios` conda channel under the name `pykealib` - just for Python 3.8/GDAL 3.2 envs at this stage. This installs a driver script `kea_build_neighbours.py` which will build the neighbours for a given file (assuming it contains the 'Histogram' column). To read out neighbours for given rows:
```
import awkward
from kea import extrat
help(extrat.getNeighbours)
```

**Comment by gillins** [comment]
@petescarth @petebunting @shepjd @neilflood any objections to this approach? I'm tempted to merge it in and make it available next time there is a release...

**Comment by petescarth** [comment]
@gillins I can confirm that the process works for me, and will be handy for a few important tasks. e.g. Determining adjacent land condition which might help prioritize remediation or even guide segmentation approaches. Doing this in vector space is a nightmare for complex or many segments so I'm in favor of this being generally available.

**Pull request merged**
